### ISSUE TITLE
Ao iniciar server, roda apenas os 2 primeiros requests, depois da erro.

### ISSUE THREAD

**Issue by samuelreichert** [samuelreichert/feevale-servidor-sistemas-distribuidos#9]
Primeiro, mudei a quantidade de palavras por cada pedaço do texto para 10.

Como exemplo utilizei: `node index.js -c http://localhost:5050 http://localhost:5051 http://localhost:5052 -s lorem -f test/fixtures/example.txt` e o retorno foi:

STATUS: 200
{ search: 'lorem', ocurrences: 1 }
No more data in response.

STATUS: 200
{ search: 'lorem', ocurrences: 1 }
No more data in response.

STATUS: 500
undefined:1
<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/styles
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/samuel/Projects/feevale/feevale-servidor-sistemas-distribuidos/index.js:98:22)
    at IncomingMessage.emit (events.js:107:17)
    at IncomingMessage.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)

**Comment by paulodiovani** [comment]
Sugiro separar essas funções em módulos e testar independentemente.
Tá difícil entender a app como um todo.

**Comment by samuelreichert** [comment]
Sugiro que não temos tempo para separa tudo até hoje a noite

**Comment by paulodiovani** [comment]
Estou vendo esse bug.
Após resolvermos podemos separar e testar os módulos.

**Comment by samuelreichert** [comment]
Sim

**Comment by paulodiovani** [comment]
Achei o problema. Está no client :D

**Comment by paulodiovani** [comment]
Corrigido no client (serviço REST): https://github.com/paulodiovani/feevale-word-counter-rest-2015/pull/2
